### ISSUE TITLE
OMIM has split Nemaline Myopathy 5 into 3 subtypes

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#1206]
OMIM has split nemaline myopathy 5 into 3 subtypes

Existing DO term DOID:0110936 has a definition that covers 5A and 5B (both recessive forms with mutations in TNNT1) but does not cover 5C (dominant form).

Consider adding new terms for the subtypes
OMIM IDs

- 605355 
- 620386
- 620389 

Existing Do term could be relabeled as autosomal recessive nemaline myopathy 5 and used as the parent term for the 2 recessive subtypes. Difference between 5A and 5B is age of onset and severity. I think for model organisms retaining the recessive onset neutral parent would be helpful.

**Comment by lschriml** [comment]
Thank you Sue, I will take a look and get the integrated. 
Cheers,
Lynn

**Comment by lschriml** [comment]
Done

**Comment by allenbaron** [comment]
The diseases 'nemaline myopathy 5B' and 'nemaline myopathy 5C' were accidentally added in the June 2023 release (v2023-06-29) with **_duplicate IRIs_** matching historically obsoleted diseases, and these errors persisted in the July releases (v2023-07-20 & v2023-07-24). We have deleted those IRIs and re-created these diseases with new, unique IRIs  in the latest release [v2023-08-08](https://github.com/DiseaseOntology/HumanDiseaseOntology/releases/tag/v2023-08-08). If you have used these diseases with their duplicate IRIs, please update to the new, unique IRIs.

disease | incorrect, duplicate IRI | new, unique IRI
-- | -- | --
nemaline myopathy 5B | `http://purl.obolibrary.org/obo/DOID_0080003` | `http://purl.obolibrary.org/obo/DOID_0081374`
nemaline myopathy 5C | `http://purl.obolibrary.org/obo/DOID_0080004` | `http://purl.obolibrary.org/obo/DOID_0081375`

_We apologize for any inconvenience this may cause._
